# Generated by Django 2.2.28 on 2022-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0003_employee_desi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='desi',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('green', 'GREEN'), ('blue', 'BLUE'), ('red', 'RED'), ('orange', 'ORANGE'), ('black', 'BLACK')], default='green', max_length=6),
        ),
    ]
