# Generated by Django 2.2.28 on 2022-06-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0004_auto_20220603_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('Employee', 'Employee')], default='manager', max_length=6),
        ),
    ]
