# Generated by Django 2.2.28 on 2022-06-03 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0005_auto_20220603_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('Employee', 'Employee'), ('semimanager', 'Semi-Manager')], default='manager', max_length=11),
        ),
        migrations.CreateModel(
            name='rem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfrom', models.DateTimeField(auto_now_add=True)),
                ('dto', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omnidash.employee')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfrom', models.DateTimeField(auto_now_add=True)),
                ('dto', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=250)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omnidash.employee')),
            ],
        ),
    ]
