# Generated by Django 2.2.28 on 2022-06-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0006_auto_20220603_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='rem',
            old_name='name',
            new_name='username',
        ),
    ]
