# Generated by Django 2.2.28 on 2022-06-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0008_auto_20220603_1716'),
    ]

    operations = [
        migrations.DeleteModel(
            name='leave',
        ),
        migrations.DeleteModel(
            name='rem',
        ),
    ]
