# Generated by Django 2.2.28 on 2022-06-03 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0009_auto_20220603_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='rem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfrom', models.DateTimeField(auto_now_add=True)),
                ('dto', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omnidash.employee')),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfrom', models.DateTimeField(auto_now_add=True)),
                ('dto', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=250)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omnidash.employee')),
            ],
        ),
    ]
