# Generated by Django 2.2.28 on 2022-06-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0010_leave_rem'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='reportingmanager',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
