# Generated by Django 2.2.28 on 2022-06-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0011_leave_reportingmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('of', 'Offline'), ('on', 'online')], default='of', max_length=10),
        ),
        migrations.AddField(
            model_name='rem',
            name='reportingmanager',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
