# Generated by Django 2.2.28 on 2022-06-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0012_auto_20220603_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=10),
        ),
    ]
