# Generated by Django 2.2.28 on 2022-06-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0013_auto_20220603_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approve',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
        migrations.AddField(
            model_name='leave',
            name='reject',
            field=models.BooleanField(default=False, verbose_name='Reject'),
        ),
        migrations.AddField(
            model_name='rem',
            name='approve',
            field=models.BooleanField(default=False, verbose_name='Approve'),
        ),
        migrations.AddField(
            model_name='rem',
            name='reject',
            field=models.BooleanField(default=False, verbose_name='Reject'),
        ),
    ]
