# Generated by Django 2.2.28 on 2022-06-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0014_auto_20220606_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='reject',
        ),
        migrations.RemoveField(
            model_name='rem',
            name='reject',
        ),
        migrations.AlterField(
            model_name='leave',
            name='approve',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='rem',
            name='approve',
            field=models.CharField(max_length=15),
        ),
    ]
