# Generated by Django 2.2.28 on 2022-06-07 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0016_auto_20220606_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='att',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dadded', models.DateTimeField(auto_now_add=True)),
                ('d1', models.CharField(max_length=15)),
                ('d2', models.CharField(max_length=15)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omnidash.employee')),
            ],
        ),
    ]
