# Generated by Django 2.2.28 on 2022-06-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0017_att'),
    ]

    operations = [
        migrations.AddField(
            model_name='att',
            name='reportingmanager',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
