# Generated by Django 2.2.28 on 2022-06-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0018_att_reportingmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='att',
            name='dadded',
            field=models.DateField(auto_now_add=True),
        ),
    ]
