# Generated by Django 2.2.28 on 2022-06-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0019_auto_20220607_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='dfrom',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='dto',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rem',
            name='dfrom',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rem',
            name='dto',
            field=models.DateField(auto_now_add=True),
        ),
    ]
