# Generated by Django 2.2.28 on 2022-06-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0021_auto_20220607_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='rem',
            name='dis',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rem',
            name='value',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
