# Generated by Django 2.2.28 on 2022-06-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0022_auto_20220607_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rem',
            old_name='dfrom',
            new_name='dadded',
        ),
        migrations.RemoveField(
            model_name='rem',
            name='dto',
        ),
        migrations.AddField(
            model_name='rem',
            name='adv',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rem',
            name='cat',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rem',
            name='loc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rem',
            name='mof',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rem',
            name='pname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
