# Generated by Django 2.2.28 on 2022-06-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0023_auto_20220607_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Employee', 'Employee'), ('Semi-Manager', 'Semi-Manager'), ('Accounts', 'Accounts')], default='manager', max_length=11),
        ),
    ]
