# Generated by Django 2.2.28 on 2022-06-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0024_auto_20220608_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='rem',
            name='pay',
            field=models.BooleanField(default=False, verbose_name='Payment-Status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], default='Offline', max_length=20),
        ),
    ]
