# Generated by Django 2.2.28 on 2022-06-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omnidash', '0025_auto_20220615_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Employee', 'Employee'), ('Semi-Manager', 'Semi-Manager'), ('Accounts', 'Accounts')], default='manager', max_length=20),
        ),
    ]
